language: php

php:
  - 5.6

before_script:
  - composer self-update --no-interaction
  - composer install --no-interaction
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1

script:
  - php vendor/bin/grumphp run
